In [2]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arr = np.array(lista)

In [5]:
type(arr)

numpy.ndarray

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[1]

2

In [9]:
arr[0] + arr[5]

7

In [10]:
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matriz[0]

array([1, 2, 3])

In [11]:
matriz[0,2]

3

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [19]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [18]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[::3]

array([1, 4, 7])

In [21]:
arr[-1]

9

In [22]:
arr[-3:]

array([7, 8, 9])

In [23]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])