In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
trozo_de_arr = arr[0:6]

In [8]:
trozo_de_arr 

array([0, 1, 2, 3, 4, 5])

In [10]:
trozo_de_arr [:] = 0
trozo_de_arr 

array([0, 0, 0, 0, 0, 0])

In [11]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr


array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])