In [3]:
import numpy as np


In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [6]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [7]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[40,45,2]],[[1,2,3],[4,5,6],[7,8,9],[40,45,2]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [40 45  2]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [40 45  2]]]


3

#agregar o eliminar dimensiones


In [10]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [11]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [12]:
print (vector, vector.ndim)
vector_2 = np.squeeze(vector)
print (vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
