In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)


In [3]:
matriz = arr.reshape(2,5)
matriz

array([[ 6, 16, 12,  1,  3],
       [ 7,  7, 16,  2, 10]])

In [4]:
arr.max()

16

In [6]:
matriz

array([[ 6, 16, 12,  1,  3],
       [ 7,  7, 16,  2, 10]])

In [5]:
matriz.max()

16

In [7]:
matriz.max(1)

array([16, 16])

In [8]:
matriz.max(0)

array([ 7, 16, 16,  2, 10])

In [9]:
arr.argmax()

1

In [10]:
matriz.argmax(0)

array([1, 0, 1, 1, 1])

In [11]:
arr.min()

1

In [12]:
matriz.min(0)

array([ 6,  7, 12,  1,  3])

In [14]:
arr

array([ 6, 16, 12,  1,  3,  7,  7, 16,  2, 10])

In [13]:
arr.argmin()

3

In [16]:
matriz

array([[ 6, 16, 12,  1,  3],
       [ 7,  7, 16,  2, 10]])

In [17]:
matriz.argmin(0)

array([0, 1, 0, 0, 0])

In [18]:
matriz.argmin(1)

array([3, 3])

In [20]:
arr


array([ 6, 16, 12,  1,  3,  7,  7, 16,  2, 10])

In [19]:
arr.ptp()

15

In [22]:
matriz.ptp(0)

array([1, 9, 4, 1, 7])

In [29]:
arr.sort()
arr

array([ 1,  2,  3,  6,  7,  7, 10, 12, 16, 16])

In [28]:
np.percentile(arr,100)

16.0

In [30]:
np.median(arr)

7.0

In [31]:
np.median(matriz,0)

array([ 4. ,  6. ,  7.5, 11. , 11.5])

In [32]:
np.std(arr)

5.138093031466052

In [33]:
np.var(arr)

26.4

In [34]:
np.mean(arr)

8.0

In [37]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [39]:
np.concatenate((a,b),axis=0)


ValueError: ignored

In [40]:
a.ndim
b.ndim

1

In [41]:
b = np.expand_dims(b,axis=0)

In [42]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
np.concatenate((a,b),axis=1)

ValueError: ignored

In [44]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
b.T

array([[5],
       [6]])